### ISSUE TITLE
Codon counts

### ISSUE THREAD

**Issue by bioinf-github** [kshulgina/codetta#2]
Hi @kshulgina ,

Really cool tool!!

I was wondering if it's possible to tell from the codetta output how many times each codon was analyzed?

e.g. there were a total of 1000 TTT codons analyzed.

(I assume this is different to "N consensus columns" as multiple Pfams can align to the same genomic location?)

Thanks!

**Comment by kshulgina** [comment]
Thanks for your interest! The "N consensus columns" is the value you are looking for-- it refers to the number of unique genomic locations of the codon that had a Pfam position aligned and were subsequently used in the analysis. 

In the next version of Codetta (which should be released imminently and is currently in the other branch), we use clearer terminology to describe how many consensus columns are aligned.
