### ISSUE TITLE
Display also standard code in the output

### ISSUE THREAD

**Issue by Anto007** [kshulgina/codetta#4]
Cool tool and thank you for bringing this out to the community! May I make a minor suggestion- can codetta also display the standard code right below the inferred genetic code of the input sequence? I think this would be convenient for many users.

**Comment by kshulgina** [comment]
Thank you for the suggestion! I will keep it in mind for the next release of Codetta.

FYI, this information provided in a longer format in the inference output file. For each codon, the Codetta amino acid inference is shown alongside the standard genetic code amino acid and an indication of whether there is a difference.

**Comment by Anto007** [comment]
Thank you for your response; Sorry, I just noticed that part in the inference output file.  As a user, I was wondering if you could make the next version of your tool say directly in the output that the predicted genetic code is likely 1-std code or 5-invertebrate mitochondrial code & so on or in case the predicted genetic code of the input genome deviates from any of the known codes, say something like- "the predicted code deviates from code 5 at two positions". A scenario where such a feature would be quite useful is when a user needs to run multiple genomes on Codetta and it becomes quite cumbersome to inspect in detail each of the longer format output files. Thanks again for your efforts

**Comment by kshulgina** [comment]
Thanks again for your suggestions. If you are analyzing many genomes, I recommend using the --results_summary option. With this option, a comma-delimited one-line summary of the genetic code inference is appended to the specified file. So if you are analyzing a large number of genomes, you will end up with one file with all of the Codetta results. This file can then be filtered/sorted/analyzed further using command line tools or as a spreadsheet. Hope that helps!
